name: Execute on devblog master-push

on:
  repository_dispatch:
    types: do-trigger-jekyll2cms
    
jobs:
  executeJekyll2cms:
    env:
      REPOSITORY_LOCAL_USER_MAIL: ${{secrets.REPOSITORY_LOCAL_USER_MAIL}}
      REPOSITORY_LOCAL_USER_NAME: ${{secrets.REPOSITORY_LOCAL_USER_NAME}}
      REPOSITORY_LOCAL_USER_PASSWORD: ${{secrets.REPOSITORY_LOCAL_USER_PASSWORD}}
      REPOSITORY_REMOTE_URL: ${{secrets.REPOSITORY_REMOTE_URL}}
      SPRING_MAIL_PASSWORD: ${{secrets.SPRING_MAIL_PASSWORD}}
      SPRING_MAIL_RECEIPIENT: ${{secrets.SPRING_MAIL_RECEIPIENT}}
      SPRING_MAIL_USERNAME: ${{secrets.SPRING_MAIL_USERNAME}}
      SPRING_MAIL_HOST: ${{secrets.SPRING_MAIL_HOST}}
      SPRING_MAIL_PORT: ${{secrets.SPRING_MAIL_PORT}}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${{secrets.SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${{secrets.SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}}
        
      JEKYLL2CMS_START_NOTIFICATION: ${{secrets.JEKYLL_START_NOTIFICATION}}
    name: executeJekyll2cms
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Do Something Based On Triggered Event Data
      run: | 
        echo "Event text:
        ${{ github.event.client_payload.text }}"
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: setup jekyll env
      run: sudo apt-get install ruby-full build-essential zlib1g-dev
    - name: setup jekyll env 2
      run: sudo gem install jekyll
    - name: Execute Jekyll2cms
      run: java -jar ./build/libs/*.jar
