name: Execute on devblog master-push

on: repository_dispatch

jobs:
  executeJekyll2cms:
    env:
      REPOSITORY_LOCAL_USER_MAIL: ${{secrets.REPOSITORY_LOCAL_USER_MAIL}}
      REPOSITORY_LOCAL_USER_NAME: ${{secrets.REPOSITORY_LOCAL_USER_NAME}}
      REPOSITORY_LOCAL_USER_PASSWORD: ${{secrets.REPOSITORY_LOCAL_USER_PASSWORD}}
      REPOSITORY_REMOTE_URL: ${{secrets.REPOSITORY_REMOTE_URL}}
      SPRING_MAIL_PASSWORD: ${{secrets.SPRING_MAIL_PASSWORD}}
      SPRING_MAIL_RECEIPIENT: ${{secrets.SPRING_MAIL_RECEIPIENT}}
      SPRING_MAIL_USERNAME: ${{secrets.SPRING_MAIL_USERNAME}}
    name: executeJekyll2cms
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Execute Jekyll2cms
      run: java -jar ./build/libs/jekyll2cms-0.0.1-SNAPSHOT.jar
