name: Generate and push XML for new blogpost

on:
  push:
    branches: 
      - master
# Implement after first test iteration
#  repository_dispatch:
#    types: do-trigger-jekyll2cms

jobs:
  build-jekyll2cms-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        
      - name: Build Docker image
        run: docker build . --tag jekyll2cms
        
  run-jekyll2cms-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: Run Docker image
        run: docker run jekyll2cms
