name: Jekyll2cms create release when push on master

on: 
  push:
    branches: 
      - master

jobs:
  buildJekyll2cms:
    name: buildJekyll2cms
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
    - uses: actions/setup-java@v1
        with:
          java-version: 1.8
    - name: Build with Gradle
        run: ./gradlew build

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE.md
          ./build/libs/*.jar
